version: 1
update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    default_reviewers:
      - "maruTA-bis5"
    commit_message:
      prefix: "chore"
      include_scope: true
