name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.5
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('**/pom.xml') }}
      - run: mvn clean verify -DskipTests=true --show-version
  test-with-server:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mattermost-version: [5.18.0,5.17.2,5.16.4,5.9.7]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.5
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('**/pom.xml') }}
      - run: docker-compose up -d
        env:
          MATTERMOST_VERSION: ${{ matrix.mattermost-version }}
      - run: mvn clean verify --show-version
  sonarqube:
    needs: [test-with-server]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11.0.5
      - run: docker-compose up -d
        env:
          MATTERMOST_VERSION: 5.18.0
      - run: mvn clean verify sonar:sonar --show-version -s .github/workflows/settings-sonar.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
